### ISSUE TITLE
strange color & gap at gradient edge

### ISSUE THREAD

**Issue by Rplus** [LeaVerou/conic-gradient#4]
``` scss
// demo code
$circle-count: 18;

.circle {
  background-image:
    repeating-conic-gradient(
      #fff 0 #{180deg / $circle-count},
      #000 0 #{360deg / $circle-count}
    );
}
```

reproduce: 
https://jsbin.com/cofege/1/edit?css,output

![image](https://cloud.githubusercontent.com/assets/1808835/8273757/0d8ec0c4-18ad-11e5-9162-de8861d3bd05.png)
